sudo: false
language: ruby
dist: trusty
osx_image: xcode9.3
os:
  - linux
  - osx
rvm:
  - ruby-head
  - 2.5.1
  - 2.4.1
  - jruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-3
jdk:
  - openjdk8
before_install: gem install bundler -v 1.15.0
