sudo: false
language: ruby
dist: trusty
osx_image: xcode10.1
os:
  - linux
  - osx
rvm:
  - ruby-head
  - 2.5.1
  - 2.4.1
  - jruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-3
  - rbx-2
jdk:
  - openjdk8
  - openjdk10
matrix:
  exclude:
    - os: mac # mac does not support openjdk8 on travis
      jdk: openjdk8
    - os: linux
      jdk: openjdk10
before_install: gem install bundler -v 1.15.0
